apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  strategy: {}
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      containers:
      - image: replace
        name: devsecops-container
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devsecops
  name: devsecops-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: devsecops
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-ingress
  namespace: royalprd
spec:
  defaultBackend:
    service:
      name: devsecops-svc
      port:
        number: 8080
  ingressClassName: nginx
  rules:
    - host: secdevops-royaltechnology.rcticonsulting.com
      http:
        paths:
          - backend:
              service:
                name: devsecops-svc
                port:
                  number: 8080
            path: /
            pathType: Prefix
